/**
 * ImageFederationMetadata.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package gov.va.med.imaging.federation.webservices.intf.v3;

public interface ImageFederationMetadata extends java.rmi.Remote {
    public gov.va.med.imaging.federation.webservices.types.v3.StudiesType getPatientStudyList(gov.va.med.imaging.federation.webservices.types.v3.RequestorType requestor, gov.va.med.imaging.federation.webservices.types.v3.FederationFilterType filter, java.lang.String patientId, java.lang.String transactionId, java.lang.String siteId, java.math.BigInteger authorizedSensitivityLevel, gov.va.med.imaging.federation.webservices.types.v3.FederationStudyLoadLevelType studyLoadLevel) throws java.rmi.RemoteException, gov.va.med.imaging.federation.webservices.types.v3.FederationSecurityCredentialsExpiredExceptionFaultType, gov.va.med.imaging.federation.webservices.types.v3.FederationMethodExceptionFaultType;
    public boolean postImageAccessEvent(java.lang.String transactionId, gov.va.med.imaging.federation.webservices.types.v3.FederationImageAccessLogEventType logEvent) throws java.rmi.RemoteException, gov.va.med.imaging.federation.webservices.types.v3.FederationSecurityCredentialsExpiredExceptionFaultType, gov.va.med.imaging.federation.webservices.types.v3.FederationMethodExceptionFaultType;
    public java.lang.String prefetchStudyList(java.lang.String transactionId, java.lang.String siteId, java.lang.String patientId, gov.va.med.imaging.federation.webservices.types.v3.FederationFilterType filter) throws java.rmi.RemoteException, gov.va.med.imaging.federation.webservices.types.v3.FederationSecurityCredentialsExpiredExceptionFaultType, gov.va.med.imaging.federation.webservices.types.v3.FederationMethodExceptionFaultType;
    public java.lang.String getImageInformation(java.lang.String imageUrn, java.lang.String transactionId) throws java.rmi.RemoteException, gov.va.med.imaging.federation.webservices.types.v3.FederationSecurityCredentialsExpiredExceptionFaultType, gov.va.med.imaging.federation.webservices.types.v3.FederationMethodExceptionFaultType;
    public java.lang.String getImageSystemGlobalNode(java.lang.String imageUrn, java.lang.String transactionId) throws java.rmi.RemoteException, gov.va.med.imaging.federation.webservices.types.v3.FederationSecurityCredentialsExpiredExceptionFaultType, gov.va.med.imaging.federation.webservices.types.v3.FederationMethodExceptionFaultType;
    public java.lang.String getImageDevFields(java.lang.String imageUrn, java.lang.String flags, java.lang.String transactionId) throws java.rmi.RemoteException, gov.va.med.imaging.federation.webservices.types.v3.FederationSecurityCredentialsExpiredExceptionFaultType, gov.va.med.imaging.federation.webservices.types.v3.FederationMethodExceptionFaultType;
    public java.lang.String[] getPatientSitesVisited(java.lang.String patientIcn, java.lang.String transactionId, java.lang.String siteId) throws java.rmi.RemoteException, gov.va.med.imaging.federation.webservices.types.v3.FederationSecurityCredentialsExpiredExceptionFaultType, gov.va.med.imaging.federation.webservices.types.v3.FederationMethodExceptionFaultType;
    public gov.va.med.imaging.federation.webservices.types.v3.PatientType[] searchPatients(java.lang.String searchCriteria, java.lang.String transactionId, java.lang.String siteId) throws java.rmi.RemoteException, gov.va.med.imaging.federation.webservices.types.v3.FederationSecurityCredentialsExpiredExceptionFaultType, gov.va.med.imaging.federation.webservices.types.v3.FederationMethodExceptionFaultType;
    public gov.va.med.imaging.federation.webservices.types.v3.PatientSensitiveCheckResponseType getPatientSensitivityLevel(java.lang.String transactionId, java.lang.String siteId, java.lang.String patientIcn) throws java.rmi.RemoteException, gov.va.med.imaging.federation.webservices.types.v3.FederationSecurityCredentialsExpiredExceptionFaultType, gov.va.med.imaging.federation.webservices.types.v3.FederationMethodExceptionFaultType;
    public gov.va.med.imaging.federation.webservices.types.v3.FederationStudyType getStudyFromCprsIdentifier(java.lang.String patientId, java.lang.String transactionId, java.lang.String siteId, java.lang.String cprsIdentifier) throws java.rmi.RemoteException, gov.va.med.imaging.federation.webservices.types.v3.FederationSecurityCredentialsExpiredExceptionFaultType, gov.va.med.imaging.federation.webservices.types.v3.FederationMethodExceptionFaultType;
    public gov.va.med.imaging.federation.webservices.types.v3.FederationVistaRadActiveExamsType getActiveWorklist(java.lang.String transactionId, java.lang.String siteId, java.lang.String listDescriptor) throws java.rmi.RemoteException, gov.va.med.imaging.federation.webservices.types.v3.FederationSecurityCredentialsExpiredExceptionFaultType, gov.va.med.imaging.federation.webservices.types.v3.FederationMethodExceptionFaultType;
    public gov.va.med.imaging.federation.webservices.types.v3.FederationVistaRadExamType[] getPatientExams(java.lang.String transactionId, java.lang.String siteId, java.lang.String patientIcn, boolean fullyLoaded) throws java.rmi.RemoteException, gov.va.med.imaging.federation.webservices.types.v3.FederationSecurityCredentialsExpiredExceptionFaultType, gov.va.med.imaging.federation.webservices.types.v3.FederationMethodExceptionFaultType;
    public java.lang.String getVistaRadRadiologyReport(java.lang.String transactionId, java.lang.String studyUrn) throws java.rmi.RemoteException, gov.va.med.imaging.federation.webservices.types.v3.FederationSecurityCredentialsExpiredExceptionFaultType, gov.va.med.imaging.federation.webservices.types.v3.FederationMethodExceptionFaultType;
    public java.lang.String getVistaRadRequisitionReport(java.lang.String transactionId, java.lang.String studyUrn) throws java.rmi.RemoteException, gov.va.med.imaging.federation.webservices.types.v3.FederationSecurityCredentialsExpiredExceptionFaultType, gov.va.med.imaging.federation.webservices.types.v3.FederationMethodExceptionFaultType;
    public gov.va.med.imaging.federation.webservices.types.v3.FederationVistaRadExamImagesType getExamImagesForExam(java.lang.String transactionId, java.lang.String studyUrn) throws java.rmi.RemoteException, gov.va.med.imaging.federation.webservices.types.v3.FederationSecurityCredentialsExpiredExceptionFaultType, gov.va.med.imaging.federation.webservices.types.v3.FederationMethodExceptionFaultType;
    public java.lang.String[] getRelevantPriorCptCodes(java.lang.String transactionId, java.lang.String cptCode, java.lang.String siteId) throws java.rmi.RemoteException, gov.va.med.imaging.federation.webservices.types.v3.FederationSecurityCredentialsExpiredExceptionFaultType, gov.va.med.imaging.federation.webservices.types.v3.FederationMethodExceptionFaultType;
    public gov.va.med.imaging.federation.webservices.types.v3.FederationVistaRadPatientRegistrationType getNextPatientRegistration(java.lang.String transactionId, java.lang.String siteId) throws java.rmi.RemoteException, gov.va.med.imaging.federation.webservices.types.v3.FederationSecurityCredentialsExpiredExceptionFaultType, gov.va.med.imaging.federation.webservices.types.v3.FederationMethodExceptionFaultType;
    public gov.va.med.imaging.federation.webservices.types.v3.FederationVistaRadExamType getPatientExam(java.lang.String transactionId, java.lang.String studyUrn) throws java.rmi.RemoteException, gov.va.med.imaging.federation.webservices.types.v3.FederationSecurityCredentialsExpiredExceptionFaultType, gov.va.med.imaging.federation.webservices.types.v3.FederationMethodExceptionFaultType;
    public java.lang.String remoteMethodPassthrough(java.lang.String transactionId, java.lang.String siteId, java.lang.String methodName, gov.va.med.imaging.federation.webservices.types.v3.FederationRemoteMethodParameterType[] parameters, java.lang.String imagingContextType) throws java.rmi.RemoteException, gov.va.med.imaging.federation.webservices.types.v3.FederationSecurityCredentialsExpiredExceptionFaultType, gov.va.med.imaging.federation.webservices.types.v3.FederationMethodExceptionFaultType;
    public boolean postVistaRadExamAccessEvent(java.lang.String transactionId, java.lang.String siteId, java.lang.String inputParameter) throws java.rmi.RemoteException, gov.va.med.imaging.federation.webservices.types.v3.FederationSecurityCredentialsExpiredExceptionFaultType, gov.va.med.imaging.federation.webservices.types.v3.FederationMethodExceptionFaultType;
}
